import React from 'react';
import Link from 'next/link';
import { curriculum } from '@/lib/content/curriculum';

export const metadata = {
  title: 'Interactive Labs | FastAPI Mastery',
  description: 'Practice real-world engineering scenarios and system design challenges.',
};

export default function LabsPage() {
  // Aggregate all challenges and scenarios across the curriculum
  const allLabs = curriculum.flatMap(chapter => 
    chapter.lessons.flatMap(lesson => 
      [
        ...lesson.challenges.map(c => ({ type: 'challenge' as const, data: c, chapter, lesson })),
        ...lesson.realWorldScenarios.map(s => ({ type: 'scenario' as const, data: s, chapter, lesson }))
      ]
    )
  );

  const challenges = allLabs.filter(l => l.type === 'challenge');
  const scenarios = allLabs.filter(l => l.type === 'scenario');

  return (
    <main className="min-h-screen bg-slate-50 pt-24 pb-32">
      <div className="container mx-auto px-6 max-w-7xl">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 mb-6">Interactive <span className="text-orange-500">Labs</span></h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Test your knowledge against real-world production incidents, system design challenges, and debugging exercises.
          </p>
        </div>

        {/* Challenges Section */}
        <div className="mb-20">
          <h2 className="text-2xl font-black text-slate-900 mb-8 flex items-center">
            <span className="w-8 h-8 rounded-lg bg-orange-100 text-orange-600 flex items-center justify-center mr-3 text-sm">🧪</span>
            Engineering Challenges
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {challenges.map((lab, idx) => (
              <div key={`c-${idx}`} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow group flex flex-col">
                <div className="flex justify-between items-start mb-4">
                  <span className="px-2.5 py-1 bg-slate-100 text-slate-600 text-xs font-bold uppercase tracking-wider rounded-md">
                    Ch {lab.chapter.id}
                  </span>
                  <span className="text-xl">💻</span>
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-2 leading-tight">{lab.data.title || 'Engineering Challenge'}</h3>
                <p className="text-slate-600 text-sm mb-6 flex-grow line-clamp-3">
                  {'description' in lab.data ? lab.data.description : 'Solve this backend architecture challenge.'}
                </p>
                <Link href={`/learn/${lab.chapter.slug}/${lab.lesson.slug}`} className="mt-auto inline-flex items-center text-sm font-bold text-orange-500 hover:text-orange-600 group-hover:translate-x-1 transition-transform">
                  Start Lab <span className="ml-1">→</span>
                </Link>
              </div>
            ))}
            
            {/* Fallback dummy labs if none exist yet */}
            {challenges.length === 0 && (
              <div className="col-span-full text-center py-12 bg-white border border-slate-200 rounded-2xl border-dashed">
                <p className="text-slate-500 font-medium">Labs are currently being generated by our engineering subagents.</p>
              </div>
            )}
          </div>
        </div>

        {/* Scenarios Section */}
        <div>
          <h2 className="text-2xl font-black text-slate-900 mb-8 flex items-center">
            <span className="w-8 h-8 rounded-lg bg-red-100 text-red-600 flex items-center justify-center mr-3 text-sm">🔥</span>
            Failure Scenarios & Incident Response
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {scenarios.map((lab, idx) => (
              <div key={`s-${idx}`} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow group">
                <div className="flex justify-between items-start mb-4">
                  <span className="px-2.5 py-1 bg-red-50 text-red-600 border border-red-100 text-xs font-bold uppercase tracking-wider rounded-md">
                    Incident
                  </span>
                  <span className="px-2.5 py-1 bg-slate-100 text-slate-600 text-xs font-bold uppercase tracking-wider rounded-md">
                    Ch {lab.chapter.id}
                  </span>
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-3 leading-tight">
                  {'scenario' in lab.data ? lab.data.scenario : 'Production Incident'}
                </h3>
                <div className="bg-slate-50 p-4 rounded-lg mb-6 border border-slate-100 text-sm text-slate-700">
                  <strong className="text-slate-900 block mb-1">The Problem:</strong>
                  {'problem' in lab.data ? lab.data.problem : 'System failure detected.'}
                </div>
                <Link href={`/learn/${lab.chapter.slug}/${lab.lesson.slug}`} className="inline-flex items-center text-sm font-bold text-red-500 hover:text-red-600 group-hover:translate-x-1 transition-transform">
                  Investigate & Fix <span className="ml-1">→</span>
                </Link>
              </div>
            ))}
            
            {scenarios.length === 0 && (
              <div className="col-span-full text-center py-12 bg-white border border-slate-200 rounded-2xl border-dashed">
                <p className="text-slate-500 font-medium">Failure scenarios are currently being generated.</p>
              </div>
            )}
          </div>
        </div>

      </div>
    </main>
  );
}
